name: yiscripts
description: YiScripts index builder with Isar nested models
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  isar_plus: ^1.1.5
  isar_plus_flutter_libs: ^1.1.5
  path: ^1.8.0
  sqlite3: ^2.4.0

dev_dependencies:
  build_runner: any


